<a href="https://colab.research.google.com/github/Monsterglitch/ML-NN-Collab/blob/main/Pandas%26Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# PYTHON LIST & NUMPY ARRAYS


In [ ]:
List = [1, 2, 3, 4, 5]
NumpyList = np.array([1, 2, 3, 4, 5, 6])
# Loop through and print
for i in NumpyList:
  print(i)

1
2
3
4
5
6


In [ ]:
# Python List and Numpy Array on sizes
# List + [5] -> Adds element 5 to the end of the list
# List.append(67) -> Element is added using the built-in function for Python Lists
print(List)
# List.pop() -> removes the last element from the list

[1, 2, 3, 4, 5]


In [ ]:
# In Numpy arrays elements cannot be appended because array sizes are set
NumpyList + np.array([1, 1, 1, 1, 1 ,1]) # As you can see, broadcasting takes place, but the formula looks to be the same as adding a number.
# Broadcasting -> Adding the element to each existing element in the array; keep in mind that the vectors / arrays added should all have the same size.

array([2, 3, 4, 5, 6, 7])

In [ ]:
2 * NumpyList # multiplies every element in the vector / array with 2 (element wise multiplication)
NumpyList ** 2 # squaring each element present in the array

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
2 * List # / List + List -> In Python this repeats the list items based on the number provided

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
# The above operation in Numpy array can be done in python list by the following code
List2 = []
# for i in List:
#   List2.append(i*2)
# print(List2)
List2 = [i + 3 for i in List] # List Comprehension
print(List2)

[4, 5, 6, 7, 8]


In [ ]:
# For each entry in the NumpyList, square root is calculated
np.sqrt(NumpyList)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
# For each entry in the NumpyList, Logarithm is calculated
np.log(NumpyList)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [ ]:
# For each entry in the NumpyList, Exponential is calculated
np.exp(NumpyList)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [ ]:
# For each entry in the NumpyList, Hyperbolic Tangent is calculated
np.tanh(NumpyList)
# And many more...

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ,
       0.99998771])

# DOT PRODUCT

In [ ]:
# Matrix Multiplication
a = np.array([1, 2, 3])
b = np.array([8, 9, 10])
DotProduct = 0
for i, j in zip(a, b):
  DotProduct += i * j
print(DotProduct)

56


In [ ]:
# Performing Matrix multilplication with number of each element in the array
DotProduct = 0
for i in range(len(b)): # Both matrices have the same dimension
  DotProduct += a[i] * b[i]
print(DotProduct)

56


In [ ]:
x = a * b # element wise multiplication
x

array([ 8, 18, 30])

In [ ]:
# np.sum(x) -> DotProduct result
x.sum() # Using instance methods

56

In [ ]:
# np.dot(a, b) -> Using Functions
a.dot(b) # Using instance methods

56

In [ ]:
# Using operator for getting the dot product (Note: both the vectors / Matrices must be of the same shape)
a @ b

56

In [ ]:
# Determining magnitude of the vector / matrix {sqrt(a^2 + b^2 +....)} a
Numbers = a ** 2
s = Numbers.sum()
sqrts = np.sqrt(s)
sqrts
# ~~~~~~~~~~~~~~~~~~~~~~~~~Alternate code~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# A_mag = np.sqrt((a * a).sum())
# print(A_mag)

3.7416573867739413

In [ ]:
# Determining magnitude of the vector / matrix {sqrt(a^2 + b^2 +....)} b
Numbers2 = b ** 2
s2 = Numbers2.sum()
sqrts2 = np.sqrt(s2)
sqrts2
# ~~~~~~~~~~~~~~~~~~~~~~~~~Alternate code~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# B_mag = np.sqrt((b * b).sum())
# print(B_mag)

15.652475842498529

In [ ]:
Denominator = sqrts * sqrts2
CosTheta = DotProduct / Denominator
print(CosTheta)

0.9561828874675149


In [ ]:
# Using function to determine the magnitude of a vector
np.linalg.norm(a)

3.7416573867739413

In [ ]:
# Alternate code for finding CosTheta
CosTheta2 = DotProduct / (np.linalg.norm(a) * np.linalg.norm(b))
CosTheta2

0.9561828874675149

In [ ]:
# Finding the actual angle from the cosine angle
angle = np.arccos(CosTheta2) # works with CosTheta as well
angle # in radions

0.2971225163471023

# SPEED TEST

In [ ]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds()) # shows which is faster

dt1 / dt2: 55.7691887675507


# MATRICES

In [ ]:
# In numpy, there is a built-in object named matrix that is two dimensional. To process this matrix object, it must be converted to a numpy array.
# Normal Matrices
Matrix = [[1, 2], [3, 4]]
Matrix[0] # -> Returns the first row

[1, 2]

In [ ]:
List[0][1] # -> returns the first element a11 (say for a matrix A)

2

In [ ]:
# Numpy Matrices
NumpyMatrix = np.array([[1, 2], [3, 4]])
NumpyMatrix

array([[1, 2],
       [3, 4]])

In [ ]:
# NumpyList[0][1]
NumpyMatrix[0, 1]
# Both produce the same results

2

In [ ]:
NumpyMatrix[:, 0] # -> Returns column at index 0

array([1, 3])

In [ ]:
NumpyMatrix[1, :] # -> Returns row at index 1

array([3, 4])

In [ ]:
NumpyMatrix.T # -> Returns transpose of the matrix

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(NumpyMatrix)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(Matrix) # Numpy can work on python lists and return a numpy array

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
NumpyMatrix2 = np.array([[10, 20], [30, 56]]) # Shapes of Matrices should be same for Matrix Multiplication
NumpyMatrix2

array([[10, 20],
       [30, 56]])

In [ ]:
# Multiplying NumpyMatrix and NumpyMatrix2
NumpyMatrix.dot(NumpyMatrix2)

array([[ 70, 132],
       [150, 284]])

In [ ]:
np.linalg.det(NumpyMatrix) # -> Returns the determinant of the Matrix

-2.0000000000000004

In [ ]:
np.linalg.inv(NumpyMatrix).dot(NumpyMatrix) # By multiplying the returned result by the initial matrix, we can see if it is inverse.

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(NumpyMatrix)

5

In [ ]:
# np.diag() is an overloaded function
np.diag(NumpyMatrix) # -> Returns the diagonal elements of the matrix

array([1, 4])

In [ ]:
np.diag([1, 4]) # -> Returns a matrix with the vector elements forming the diagonal

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(NumpyMatrix) # -> Returns two array first one with eigen values and second one with eigen vectors

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
EigenValue, EigenVector = np.linalg.eig(NumpyMatrix)
EigenValue[0] * EigenVector[:, 0] == NumpyMatrix @ EigenVector[:, 0] # -> Compares vectors of size 2 Thus a vector of size 2 is returned

array([ True, False])

In [ ]:
EigenValue[0] * EigenVector[:, 0], NumpyMatrix @ EigenVector[:, 0]
# The numbers appear to be the same as before, but the result on the right side is False because the computer does not have infinite memory to keep the elements as they are. They may be rounded off

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
# To check if the two numpy arrays are equal we use allclose() function
np.allclose(EigenVector[:, 0] * EigenValue[0], NumpyMatrix @ EigenVector[:, 0])

True

In [ ]:
# Checks are made for all the eigen vectors
np.allclose(EigenVector @ np.diag(EigenValue), NumpyMatrix @ EigenVector)

True

In [ ]:
# np.linalg.eigh() is used to return the eigen values and vectors for a real symmetric matrix
# "h" in eigh -> is an abbreviation for complex analogue of matrix transpose. "It requires the elements' transpose as well as their complex conjugate."

In [ ]:
# Declaring a symmetric matrix
A = np.array([[2, 3, 6], [3, 4, 5], [6, 5, 9]])
A

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [ ]:
# Eigen values and vectors of a symmetric matrix
np.linalg.eigh(A)

(array([-1.45033183,  1.02829753, 15.42203429]),
 array([[-0.87416716,  0.19165551, -0.44620617],
        [ 0.03695488, -0.88991075, -0.45463523],
        [ 0.48421702,  0.41391669, -0.77084814]]))