<a href="https://colab.research.google.com/github/Monsterglitch/ML-NN-Collab/blob/main/Tensorflow%26Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !nvidia-smi # use this in GPU runtime

/bin/bash: nvidia-smi: command not found


# **TENSORFLOW BASICS**

In [ ]:
# Importing Tensorflow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.13.0


## Creation of TENSORS with tf.constant()

In [ ]:
### .get_shape() works for fixed TENSORS

### Scalar

In [ ]:
constant_scalar = tf.constant(7)
constant_scalar, constant_scalar.ndim, constant_scalar.shape, constant_scalar.get_shape(), constant_scalar.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 0,
 TensorShape([]),
 TensorShape([]),
 tf.int32)

### Vector

In [ ]:
constant_vector = tf.constant([1, 2])
constant_vector, constant_vector.ndim, constant_vector.shape, constant_vector.get_shape(), constant_vector.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 1,
 TensorShape([2]),
 TensorShape([2]),
 tf.int32)

### MATRIX

In [ ]:
constant_MATRIX = tf.constant([[1., 2.],
                               [3., 4.]], dtype = "float16")
constant_MATRIX, constant_MATRIX.ndim, constant_MATRIX.shape, constant_MATRIX.get_shape(), constant_MATRIX.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float16)>,
 2,
 TensorShape([2, 2]),
 TensorShape([2, 2]),
 tf.float16)

### TENSOR

In [ ]:
constant_TENSOR = tf.constant(value=[1, 2, 3, 4, 5, 6,
                                     7, 8, 9, 10, 11, 12], shape=(2, 2, 3), dtype = tf.float32) # "shape" argument changes the type of tensors
constant_TENSOR, constant_TENSOR.ndim, constant_TENSOR.shape, constant_TENSOR.get_shape(), constant_TENSOR.dtype

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],
 
        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=float32)>,
 3,
 TensorShape([2, 2, 3]),
 TensorShape([2, 2, 3]),
 tf.float32)

### Trying to change the constant TENSOR'S values

In [ ]:
# constant TENSOR'S values cannot be changed

In [ ]:
# constant_TENSOR[1, 1, 1] = 9
# constant_TENSOR
# Error -> 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# constant_TENSOR[1, 1, 1].assign(9)
# constant_TENSOR
# Error -> 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creation of TENSORS with tf.Variable()

In [ ]:
### .ndim doesn't work in variable TENSORS

In [ ]:
variable_TENSOR = tf.Variable([[1, 2.2],
                               [9, 0.8]])
variable_TENSOR, variable_TENSOR.shape, variable_TENSOR.dtype

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
 array([[1. , 2.2],
        [9. , 0.8]], dtype=float32)>,
 TensorShape([2, 2]),
 tf.float32)

### Trying to change the variable TENSOR'S values

In [ ]:
# variable_TENSOR[1][2] = 3.4
# variable_TENSOR
# Error -> 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
# using .assign()
variable_TENSOR[1, 0].assign(3.58)
variable_TENSOR

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1.  , 2.2 ],
       [3.58, 0.8 ]], dtype=float32)>

## Creation of Random *TENSOR*

### Output random values from a normal distribution

In [ ]:
# Reproduce this same TENSOR by setting a seed value
random_TENSOR1 = tf.random.Generator.from_seed(2)
random_TENSOR1 = random_TENSOR1.normal(shape = (5, 5))
random_TENSOR1, random_TENSOR1.ndim, random_TENSOR1.shape, random_TENSOR1.get_shape(), random_TENSOR1.dtype
# All the above functions work for random TENSORS

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924],
        [-1.9633987 , -0.06452483, -1.056841  ,  1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ,  1.0278524 ,  0.27974114, -0.01347923],
        [ 1.845181  ,  0.97061104, -1.0242516 , -0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644]],
       dtype=float32)>,
 2,
 TensorShape([5, 5]),
 TensorShape([5, 5]),
 tf.float32)

## Shuffle a TENSOR

[Know about global & operation-level seeds](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [ ]:
TENSOR_to_be_Shuffled1 = tf.constant([[1, 2],
                                      [3, 4],
                                      [5, 6]])
tf.random.set_seed(8) # (global seed) After setting the seed the shuffle is the same on all runs
TENSOR_Shuffled1 = tf.random.shuffle(TENSOR_to_be_Shuffled1, seed = 8) # (operation-level seed) Argument seed alone is not sufficient
TENSOR_Shuffled1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

## Creation of TENSORS from NumPY Arrays

In [ ]:
TENSOR_from_NumPY = tf.Variable(np.array([[89, 11],
                                          [13, 4]]), dtype = np.int64)
TENSOR_from_NumPY, TENSOR_from_NumPY.shape, TENSOR_from_NumPY.get_shape(), TENSOR_from_NumPY.dtype

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
 array([[89, 11],
        [13,  4]])>,
 TensorShape([2, 2]),
 TensorShape([2, 2]),
 tf.int64)

## Reshape a TENSOR

In [ ]:
reshape_TENSOR1 = tf.Variable([7., 8., 2., 1., 0., 5.]) # Shape argument in tf.Variable doesn't change the shape of the  initial value given
reshape_TENSOR1 = tf.reshape(reshape_TENSOR1, shape = (2, 3)) # Use tf.reshape() instead
# --- ALTERNATE WAY ---
reshape_TENSOR2 = tf.Variable(np.array(range(0, 6)).reshape((2, 3)), shape = (2, 3), dtype = tf.float16)
reshape_TENSOR1, reshape_TENSOR2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[7., 8., 2.],
        [1., 0., 5.]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float16, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float16)>)

# **TENSORFLOW Sample Work Flow**

In [ ]:
# Beginner Starter Code
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

11490434/11490434 [==============================] - 2s 0us/step
Epoch 1/5
1875/1875 [==============================] - 13s 3ms/step - loss: 0.2982 - accuracy: 0.9154
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1464 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1073 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0870 - accuracy: 0.9732
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0717 - accuracy: 0.9778


[0.07168933749198914, 0.9778000116348267]

In [ ]:
# Generate a tensor of size [5, 3] with random values between 0 and 1
tensor1 = tf.random.uniform([5, 3])
print(tensor1, "\n")
# Generate a random float between 0 and 1
random_float = tf.random.uniform(shape=([1, 2, 3]), minval=0, maxval=1)
print(random_float, "\n")
# Generate a random integer between 0 and 9
random_int = tf.random.uniform(shape=(), minval=0, maxval=10, dtype=tf.int32)
print(random_int, "\n")
# Generate a random boolean value
random_bool = tf.random.uniform(shape=(), minval=0, maxval=2, dtype=tf.int32) == 1
print(random_bool, "\n")

tf.Tensor(
[[0.6545346  0.85802853 0.84777534]
 [0.31908548 0.61795485 0.69293845]
 [0.21390617 0.85044956 0.4994247 ]
 [0.88213956 0.6740403  0.9059944 ]
 [0.11097276 0.20140111 0.8460798 ]], shape=(5, 3), dtype=float32) 

tf.Tensor(
[[[4.5802796e-01 6.0263765e-01 8.3097243e-01]
  [3.4060359e-01 4.3630600e-05 8.0483401e-01]]], shape=(1, 2, 3), dtype=float32) 

tf.Tensor(8, shape=(), dtype=int32) 

tf.Tensor(True, shape=(), dtype=bool) 



In [ ]:
# Generate a random tensor of shape (3, 3) from a normal distribution
random_tensor = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)
print(random_tensor, "\n")
# Generate a random tensor of shape (2, 2) from a uniform distribution
random_tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=1)
print(random_tensor, "\n")

tf.Tensor(
[[-2.2095282   1.0112196   0.17237487]
 [ 0.87286896 -0.9127773  -0.21118803]
 [ 0.6596108  -0.3018419   2.0745454 ]], shape=(3, 3), dtype=float32) 

tf.Tensor(
[[0.55669236 0.3356161 ]
 [0.74592817 0.88962877]], shape=(2, 2), dtype=float32) 



# **PYTORCH BASICS**

In [ ]:
!pip install torch torchvision

In [ ]:
import torch
import torchvision
torch.__version__

'2.0.1+cu118'

##  Single Dimension Tensor / Scalar

In [ ]:
scalar = torch.tensor(5)
# scalar.item() # gives the value
# scalar.dtype # gives the datatype of the element within the tensor / scalar
scalar.shape, scalar.dtype, scalar.ndim # Only works with one-element tensor / scalar - getting the python number within the tensor

(torch.Size([]), torch.int64, 0)

## Vector

In [ ]:
vector = torch.tensor([10,5])
# vector.item() #-> This isn't possible since, it isn't a scalar
# vector.ndim #No. of square brackets == no. of dimensions of the tensor
vector.shape, vector.dtype, vector.ndim

(torch.Size([2]), torch.int64, 1)

## MATRIX

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX.shape, MATRIX.dtype, MATRIX.ndim

(torch.Size([2, 2]), torch.int64, 2)

## TENSOR

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR.shape, TENSOR.dtype, TENSOR.ndim

(torch.Size([1, 3, 3]), torch.int64, 3)

## TENSORS using rand, zeros and ones

In [ ]:
# Random
random1 = torch.rand(size = (5, 3), dtype = torch.float32)
random2 = torch.rand(size = (2, 5)) # alternate syntax
# Zeros - Can be used for masking
zeros1 = torch.zeros(5, 2)
zeros2 = torch.zeros(size = (3, 4))
# Ones
ones1 = torch.ones(3, 4)
ones2 = torch.ones(size = (3, 4))
random1.shape, random1.dtype, random1.ndim #-> (torch.Size([5, 3]), 5), zeros1, zeros1.dtype, ones1, ones1.dtype
# random2.shape, random2.dtype, random2.ndim, zeros2, zeros2.dtype, zeros2.ndim, ones2, ones2.dtype, ones2.ndim

(torch.Size([5, 3]), torch.float32, 2)

### Functions & Attributes

In [ ]:
# A function has "()" at the end, while the attributes of a TENSOR don't have one
op_TENSOR = torch.rand(size = (2, 2))
print(f"{op_TENSOR.shape}, {op_TENSOR.size()}")

torch.Size([2, 2]), torch.Size([2, 2])


### Changing the datatype of a TENSOR & viewing its device

In [ ]:
changing_TENSOR = torch.rand([2, 2], dtype = torch.half)
print(changing_TENSOR.dtype)
changing_TENSOR = changing_TENSOR.type(torch.float)
print(changing_TENSOR.dtype)
# changing_TENSOR.device # "cpu"

torch.float16
torch.float32


## TENSOR manipulations using arange(), zeros_like() and ones_like()

In [ ]:
# torch.range() is deprecated
# zero_to_ten_deprecated = torch.range(0, 10) # May return an error

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start = 0, end = 10, step = 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# It can also create a tensor of zeros similar to another tensor
five_zeros = torch.zeros_like(input = zero_to_ten) # same shape as the tensor "zero_to_ten"
# It creates a tensor of ones similar to another tensor
five_ones = torch.ones_like(input = zero_to_ten) # same shape as the tensor "zero_to_ten"
five_ones, five_zeros

(tensor([1, 1, 1, 1, 1]), tensor([0, 0, 0, 0, 0]))

### Multiplying TENSORS of different datatypes

In [ ]:
float_tensor = torch.tensor([[1, 2],
                             [1, 2]], dtype = torch.float)
long_tensor = torch.tensor([[2, 2],
                            [2, 2]], dtype = torch.long)
float_tensor * long_tensor

tensor([[2., 4.],
        [2., 4.]])

## Manipulating TENSORS (Addition, Subtraction, Multiplication, Division)

In [ ]:
manipulated_TENSOR1 = torch.tensor([10, 20, 30])
print(f"Manipulations using Normal Symbols: \n{manipulated_TENSOR1 + 20}, {manipulated_TENSOR1 - 5}, {manipulated_TENSOR1 * 2}, {manipulated_TENSOR1 / 5}")
print(f"Manipulations using Built-in Functions: \n{torch.add(manipulated_TENSOR1, 20)}, {torch.sub(manipulated_TENSOR1, 5)}, {torch.mul(manipulated_TENSOR1, 2)}, {torch.div(manipulated_TENSOR1, 5)}")

Manipulations using Normal Symbols: 
tensor([30, 40, 50]), tensor([ 5, 15, 25]), tensor([20, 40, 60]), tensor([2., 4., 6.])
Manipulations using Built-in Functions: 
tensor([30, 40, 50]), tensor([ 5, 15, 25]), tensor([20, 40, 60]), tensor([2., 4., 6.])


## MATRIX Multiplication

In [ ]:
TENSOR1_matmul = torch.tensor([[2, 2],
                               [2, 2]])
TENSOR2_matmul = torch.tensor([[1],
                               [1]])
torch.matmul(TENSOR1_matmul, TENSOR2_matmul) # shape - ([2, 1])

tensor([[4],
        [4]])